### ISSUE TITLE
crash at `deinit {  ...   videoDataQueue.async { [weak self] in  ... }`

### ISSUE THREAD

**Issue by Ted4kra** [mercari/QRScanner#15]
I push or present a new controller with QRScannerView(). when I pop or dismiss it , the QRScannerView.swift crash at line 137.
It seems that we can't use [weak self] at deinit method.

**Comment by hitsubunnu** [comment]
@Ted4kra Thank you for your information. We resolved it in https://github.com/mercari/QRScanner/pull/16
