### ISSUE TITLE
Value of type 'AVMetadataMachineReadableCodeObject' has no member 'corners'

### ISSUE THREAD

**Issue by arqambutt** [mercari/QRScanner#18]
can anyone tell me how to fix this error?

**Comment by voyager163** [comment]
Hi,

This error is due to Apple. Someone left out the corner codes for the simulator. You still will be able to build using the devices.

You can put #if !targetEnvironment(simulator) to skip the simulator error.

**Comment by voyager163** [comment]
Hi,

As of today, you just need to update to the latest XCode. I raise the feedback previously to Apple and it is solved already.
