### ISSUE TITLE
Not working on simulator

### ISSUE THREAD

**Issue by piotrros** [mercari/QRScanner#19]
`Value of type 'AVMetadataMachineReadableCodeObject' has no member 'corners'`

QRScannerView.swift, line 350:

`strongSelf.moveImageViews(qrCode: stringValue, corners: readableObject.corners)`

Workaround:

```
#if !targetEnvironment(simulator)
strongSelf.moveImageViews(qrCode: stringValue, corners: readableObject.corners)
#endif
```

read more:
https://stackoverflow.com/questions/63939496/xcode-12-avmetadatamachinereadablecodeobject-issue

**Comment by voyager163** [comment]
Hi,

As of today, you just need to update to the latest XCode. I raise the feedback previously to Apple and it is solved already.
