### ISSUE TITLE
Custom focus image frame

### ISSUE THREAD

**Issue by adityativ** [mercari/QRScanner#26]
Please add ability to add custom frame of focus image view

**Comment by hitsubunnu** [comment]
@adityativ see: https://github.com/mercari/QRScanner#customization
```
override func viewDidLoad() {
        super.viewDidLoad()

        let qrScannerView = QRScannerView(frame: view.bounds)

        // Customize focusImage, focusImagePadding, animationDuration
        qrScannerView.focusImage = UIImage(named: "scan_qr_focus")
        qrScannerView.focusImagePadding = 8.0
        qrScannerView.animationDuration = 0.5

        qrScannerView.configure(delegate: self)
        view.addSubview(qrScannerView)
        qrScannerView.startRunning()
}
```

**Comment by AnthoPakPak** [comment]
Thanks for your library!
I have the same question, and the provided code unfortunately doesn't help.

The idea is to be able to change the position of the focus image view (`focusImageView` in the code). As of now it seem to only handle full width views (meaning that any frame that isn't full width will result in `focusImageView` not being correctly centered). Being able to set `focusImageView` frame or center would help fixing this issue.
