### ISSUE TITLE
Does this use the native service in iOS 13+?

### ISSUE THREAD

**Issue by Synchro** [mercari/QRScanner#30]
The description of this package says that it emulates the native QR scanning support of iOS 13 on older OS versions. Does that mean that if you *are* running iOS 13 or later, it acts as a simple wrapper for the built-in service and does not handle the scanning itself?

**Comment by hitsubunnu** [comment]
No, iOS don't provide the built-in scan service. QRScanner use AVFoundation to handle the scanning itself.
