### ISSUE TITLE
Reference to member 'rescan' cannot be resolved without a contextual type

### ISSUE THREAD

**Issue by umerirfan26** [mercari/QRScanner#32]
i cannot solve this error.
please help
<img width="1276" alt="Screenshot 2021-12-28 at 11 15 55 AM" src="https://user-images.githubusercontent.com/84024073/147534389-517f4c3b-af52-4a85-a2c1-204b29fc514a.png">

 self.qrScannerView.rescan().         Reference to member 'rescan' cannot be resolved without a contextual type

**Comment by hitsubunnu** [comment]
@umerirfan26 Could you confirm qrScannerView is  QRScannerView?
See: https://github.com/mercari/QRScanner/blob/master/QRScannerSample/QRScannerSample/ViewController.swift#L14

**Comment by umerirfan26** [comment]
> 

No it’s not.
I made mistake.
Now resolved.
